version: '2'
services:
  redis:
    image: redis:alpine
  heimdall-api:
    image: getheimdall/heimdall-api:latest
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    links:
    - redis:redis
    ports:
    - 9090:9090/tcp        
  heimdall-gateway:
    image: getheimdall/heimdall-gateway:latest
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    links:
    - redis:redis
    ports:
    - 8080:8080/tcp        
  heimdall-frontend:
    image: getheimdall/heimdall-frontend:latest   
    ports:
    - 80:5000/tcp        
